import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from 'sonner';
import "./globals.css";
import { NotesProvider } from "@/contexts/notes-context";
import { SearchProvider } from "@/contexts/search-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Notes Expert",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <SearchProvider>
        <NotesProvider>
          <body className={inter.className}>{children}</body>
        </NotesProvider>
      </SearchProvider>
      <Toaster richColors/>
    </html>
  );
}
